### ISSUE TITLE
why the results cannot be reproduced?

### ISSUE THREAD

**Issue by bqdeng** [gydpku/Official-pytorch-implementation-of-AOP-AAAI-2022-#1]
Hello and thank you for your excellent work! In your code, I'm having some problems. When I ran the AOP code, the result was that the forgetting was very serious, the previous task almost became 0, and I did not know if there were any details that I did not understand.

 If you like this, can you supplement the details of the experiment to distinguish when the AOP is really running successfully?

Thank you！

**Comment by bqdeng** [comment]
I can't get your results and would like your help. @gydpku

**Comment by muyuuuu** [comment]
do you solve it? I also have meet this problem..... @bqdeng

**Comment by bqdeng** [comment]
Unfortunately, we can not reproduce the author's results in the end. @muyuuuu

**Comment by gydpku** [comment]
> Unfortunately, we can not reproduce the author's results in the end. @muyuuuu

Can you reproduce the result of OCM?

**Comment by muyuuuu** [comment]
> > Unfortunately, we can not reproduce the author's results in the end. @muyuuuu
> 
> Can you reproduce the result of OCM?

https://github.com/gydpku/Official-pytorch-implementation-of-AOP-AAAI-2022-/blob/6270b4528b1db778c6148a344612df11995dd53d/Code%20for%20AOP/AOP_online_without_pre_trained/run_cifar100_AOP_online.py#L75-L97

I have run this file, here is the result:

![AOP](https://user-images.githubusercontent.com/43681138/207256158-dfb71969-47f5-413a-884c-a4312a941c97.png)

where is your pretrain code?

**Comment by gydpku** [comment]
> 

This is the code for experiment without using the pre-trained extractor. If you want to use the pre-trained extractor, you can use the pre-trained image encoder of CLIP, that is better than the extractor I trained.

**Comment by gydpku** [comment]
> 

This is the code for experiment without using the pre-trained extractor. If you want to use the pre-trained extractor, you can use the pre-trained image encoder of CLIP, that is better than the extractor I trained.

**Comment by gydpku** [comment]
> > 
> 
> This is the code for experiment without using the pre-trained extractor. If you want to use the pre-trained extractor, you can use the pre-trained image encoder of CLIP, that is better than the extractor I trained.

For the code of experiment with the pre-trained extractor, it's similar to the code of MNIST experiment.
